### ISSUE TITLE
Revisit number of metrics exported to Prometheus

### ISSUE THREAD

**Issue by adamantal** [banzaicloud/koperator#538] opened 2021-01-15 13:50 UTC
**Describe the bug**
If a specific topic has a consumer group, the metrics with the following template are pushed into Prometheus:
`kafka_server_fetcherlagmetrics_total_consumerlag_clientid_replicafetcherthread_0_<number>_topic_<topic_name>_partition_<partition number>_value`. This causing `num of topics * number of partitions` metrics to be exported into Prometheus

If there are large number of topics with high partition counts, the amount of metrics is very large. This potentially degrades Prometheus server performance.

**Steps to reproduce the issue:**
1. Create several topics with high number of partitions.
1. Upload some data to them.
1. Create consumer groups.
1. Check Prometheus UI for the list of metrics: you will find many of them.

**Expected behavior**
See a lot less metrics.

**Screenshots**
![Screenshot 2021-01-15 at 14 48 41](https://user-images.githubusercontent.com/41062664/104734665-e5cef080-5740-11eb-8b8d-415da17781f3.png)

**Additional context**
These metrics are generated by the misconfigured JMX exporter config.
The original metrics from Kafka JMXBean for reference:
```
kafka.server:clientId=ReplicaFetcherThread-0-1,name=ConsumerLag,partition=0,topic=__CruiseControlMetrics,type=FetcherLagMetrics
kafka.server:clientId=ReplicaFetcherThread-0-1,name=ConsumerLag,partition=0,topic=__KafkaCruiseControlPartitionMetricSamples,type=FetcherLagMetrics
kafka.server:clientId=ReplicaFetcherThread-0-1,name=ConsumerLag,partition=0,topic=_kafka-connect-kafka-config,type=FetcherLagMetrics
kafka.server:clientId=ReplicaFetcherThread-0-1,name=ConsumerLag,partition=1,topic=__KafkaCruiseControlModelTrainingSamples,type=FetcherLagMetrics
...
```

The JMX config can be finetuned a bit to push the topic name as labels instead of putting it into the name of the metric. Prometheus is better handling those.

**Comment by amuraru** [comment] 2021-01-17 10:51
+1 - Kafka recently also added support for filtering out metrics server side https://cwiki.apache.org/confluence/plugins/servlet/mobile?contentId=133631990#content/view/133631990 
Should we use this to filter these metrics?

**Comment by adamantal** [comment] 2021-01-18 09:01
Thanks for the link @amuraru. I think we can leverage this feature. Also, we should finetune the jmx exporter config as well.
Using both methods should be effective.

**Comment by amuraru** [comment] 2021-07-22 17:20
hi @adamantal - checked this in our environment and couldn't reproduce.

I am seeing instead:
```
# HELP kafka_server_fetcherlagmetrics_consumerlag Attribute exposed for management (kafka.server<type=FetcherLagMetrics, name=ConsumerLag, clientId=ReplicaFetcherThread-1-304, topic=cjm_ups_xport_perf_32, partition=14><>Value)
# TYPE kafka_server_fetcherlagmetrics_consumerlag gauge
kafka_server_fetcherlagmetrics_consumerlag{clientId="ReplicaFetcherThread-1-304",partition="14",topic="cjm_ups_xport_perf_32",} 0.0
kafka_server_fetcherlagmetrics_consumerlag{clientId="ReplicaFetcherThread-1-203",partition="8",topic="dx_mob_push_messages",} 0.0
kafka_server_fetcherlagmetrics_consumerlag{clientId="ReplicaFetcherThread-3-205",partition="2",topic="dx_mob_push_messages",} 0.0
kafka_server_fetcherlagmetrics_consumerlag{clientId="ReplicaFetcherThread-3-302",partition="5",topic="dx_cjm_mr_mpu_in_1",} 0.0
kafka_server_fetcherlagmetrics_consumerlag{clientId="ReplicaFetcherThread-1-202",partition="105",topic="cjm_imp_email_perf_128",} 0.0

```

Could it be that recent changes fixed that?

**Comment by adamantal** [comment] 2021-07-29 12:57
@amuraru Sorry for the late reply.
Thanks for checking this. Do you use the upstream jmx-exporter configs or a custom one? If you use the upstream one, then I'm fine to close this.

**Comment by amuraru** [comment] 2021-07-29 18:13
I am using default jmx config from the operator and not overriding

**Comment by baluchicken** [comment] 2022-01-12 10:38
Closing this since as stated above the recent change fixed the issue.

**Closed by baluchicken** 2022-01-12 10:38 UTC
