### ISSUE TITLE
Cluster stuck in ClusterRollingUpgrading state

### ISSUE THREAD

**Issue by qbast** [banzaicloud/koperator#245] opened 2020-01-10 09:16 UTC
**Describe the bug**
After about 2 months of working, cluster went into a state where only one kafka broker pod is running (instead of 3) and KafkaCluster is always stuck in ClusterRollingUpgrading state

**Steps to reproduce the issue:**
Unfortunately I do not know what triggered this. First indication of the problem was alert about underreplicated topics.

**Expected behavior**
I would expect that the controller creates 2 more kafka brokers and sets KafkaCluster status to Running.

**Additional context**
I am running operator 0.7.3 on GKE 1.14.7. Cluster is configured for 3 nodes. Some things I tried:
- restarting operator
- deleting the only running kafka broker - operator recreates it but it does not recreate 2 others
- doing kubectl edit kafkacluster to change number of brokers - it was ignored

I also noticed that PVs for two missing brokers are deleted as well.
I attached output of kubectl describe kafkacluster and verbose log from the operator.

Most important question for me: how do I get the cluster 'unstuck' without losing data?

[kafkacluster.txt](https://github.com/banzaicloud/kafka-operator/files/4044749/kafkacluster.txt)
[log.txt](https://github.com/banzaicloud/kafka-operator/files/4044796/log.txt)

**Comment by stoader** [comment] 2020-01-10 09:38
The attached kafka-operator logs have only one-day worth logs. Was the operator restarted?  If so can you get the logs from the previous operator instance to see if the two other brokers were downscaled by the operator or not?

Also if you look at Kubernetes events can you see anything about when were the two other broker pods stopped?

In your Kafka CR your brokers have 20GB volumes assigned each. Can you check if the volume is not full for the remaining broker?

cc @baluchicken

**Comment by qbast** [comment] 2020-01-10 10:10
Unfortunately I do not have older
 operator logs, but I have kubernetes audit logs that show all API operations (including deletions). 

[pod-operations.txt](https://github.com/banzaicloud/kafka-operator/files/4045047/pod-operations.txt)
[all-operations.txt](https://github.com/banzaicloud/kafka-operator/files/4045048/all-operations.txt)


First log shows only operations on pods. Last 4 lines show my manual attempts to restart kafka broker (by deleting a pod) and operator.
Second log shows all relevant API operations around the time trouble happened. As you can see the actual deletions were made by garbage collector (seems like all trouble I have with kafka controller involve garbage collector in some way).

I deleted the only running broker by simply deleting the pod with kubectl. Operator immediately noticed it not running and recreated - but only this one.
The kafka cluster has a very low volume of traffic  (not a production environment) - only 0.5GB is used.

One more thing I tried to break the operator out of its coma: editing KafkaCluster resource to change CPU request for broker. Operator noticed there is difference between running configuration and requested one, but did not do anything about it.

**Comment by baluchicken** [comment] 2020-01-10 13:38
Hi @qbast, Can you please verify that your last standing broker PVC is the original one and not deleted by the Garbage Collector. From the logs I saw three PVC deletion.
Can you please check if the running Kafka broker is healthy?
Try to connect to it using `kafkacat`.
Can you give us logs from the running Kafka broker?

The reason why to operator is stuck at rolling upgrading state is the following:
What the operator does is, it tries to interact with the Kafka cluster using the one running broker.
It does that to dynamically configure the cluster.
If it cannot connect to the one running Broker because it is unhealthy. 
It just waits until it can do the configuration.

**Comment by qbast** [comment] 2020-01-10 15:05
Hello

I checked GCP logs for persistent disk and indeed PV of the last standing broker is not original - it was created yesterday at  01:54:14.314 GMT. 

Looking at kafka broker - it is running, but it can be hardly called healthy. Some services that depend on kafka can connect and authenticate successfully, but consumers keep spamming 'partitions have leader brokers without a matching listener' errors. Other services fail authentication.

Attached is broker log :
[kafka-log-2.txt](https://github.com/banzaicloud/kafka-operator/files/4046215/kafka-log-2.txt)

Lots of authentication errors - 10.144.4.20 that is most frequent is IP of kafka-operator. So this confirms that operator is stuck because it cannot connect.

So it looks like there is nothing left to save and the only 'recovery' is to delete everything and redeploy. I don't understand why Garbage Collector to kill the pods - according to kubectl describe they don't have any owner set.

**Comment by qbast** [comment] 2020-01-10 15:18
One more log: this one shows just garbage collector actions. First thing it did was deleting KafkaUser for operator. Then it went on a rampage and started breaking everything in sight.

[garbage-collector.txt](https://github.com/banzaicloud/kafka-operator/files/4046274/garbage-collector.txt)

**Comment by gferreux** [comment] 2020-08-20 14:45
Hi, i have a similar situation, but caused by adding a PodDisruptionBudget to the kafka cluster.

Ths PDB Status is "currentHealthy: 0", because pods are running but in an UnHealty State:
Unhealthy | Readiness probe failed: Get http://<podip>:15021/healthz/ready: dial tcp <podip>:15021: connect: connection refused.

Is this du to the lack of readinessProbe on the kafka pods with istio ? how to handle that ? thanks

- cloud: GKE 1.16.11-gke.5
- operator: v0.12.0
- istio: enabled

**Comment by baluchicken** [comment] 2022-01-12 08:40
This issue should be fixed by https://github.com/banzaicloud/koperator/pull/713 so closing this please reopen if this happens.

**Closed by baluchicken** 2022-01-12 08:40 UTC

**Comment by LolloChicco** [comment] 2022-02-15 09:15
HI, I tried to upgrade the Operator to 0.20.2 to fix the bug, but since I have cluster stuck in ClusterRollingUpgrade , the upgrade doesn't work because is not on ClusterRunning state. Some help ? Thanks

**Comment by stoader** [comment] 2022-02-15 09:50
Please attach your koperator logs. Also, you can get help from. koperator's community by joining the community slack channel here:https://banzaicloud.com/invite-slack/

**Comment by stoader** [comment] 2022-07-06 07:28
@vitalii-buchyn-exa  please open separate GH issue and attach your:
- entire `koperator` logs,
- `KafkaCluster` custom resource

Alternatively, you can ask help on the community slack channel
