### ISSUE TITLE
Configure the kafka certificates with longer period

### ISSUE THREAD

**Issue by chrodrigues** [banzaicloud/koperator#964] opened 2023-04-26 22:24 UTC
## Description

I have the following scenario:

1 - Producers (logstash) are connecting on Kafka cluster using SSL.

2 - When the producer certificate expires it can't connect to the cluster due to this error:

% ERROR: Local: SSL error: ssl://kafka.mydomain.com:29092/bootstrap: SSL handshake failed: ../ssl/statem/statem_clnt.c:1913: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:  (after 368ms in state CONNECT)

3 - All times that the certificate is rotated I have to renew this one on each producer.

## Expected Behavior
I would like Kafka to generate certificates with a longer validity period.

## Actual Behavior
Kafka is generating the certificates with 3 months of validity period

## Affected Version

3.1-IV0

## Steps to Reproduce

Wait for expiration of certificate
Wait for renewal of certificate
Client connexion issue should appears

Thank you!

**Comment by panyuenlau** [comment] 2023-05-03 20:47
Hey @chrodrigues - I am seeing two different requests from this issue:
- certificate rotation (this is a duplicate of #827)
- customized validity of the generated certificates

Please correct me if I am mistaken, otherwise I think it's better to change the issue title to something like "Allow users to customize validity of generated certificates"

**Comment by panyuenlau** [comment] 2023-05-03 20:52
Hey @fquinino, the Koperator is not yet capable of allowing users to configure the validity of the certificates, the 90 days validity is the default certificate validity from cert-manager, see the `certificate.spec.duration` in here https://cert-manager.io/docs/usage/certificate/#creating-certificate-resources

**Comment by bartam1** [comment] 2023-05-11 05:44
I can confirm what @panyuenlau said: The default expiration for all certificates is 90 days. The default time before expiration when the Certificate manager service renews the certificates is 30 days.
We will fix this soon.

**Comment by chrodrigues** [comment] 2023-05-14 22:54
> Hey @fquinino, the Koperator is not yet capable of allowing users to configure the validity of the certificates, the 90 days validity is the default certificate validity from cert-manager, see the `certificate.spec.duration` in here https://cert-manager.io/docs/usage/certificate/#creating-certificate-resources

Hi @panyuenlau, thank you for your help. It's worked for me.

**Comment by panyuenlau** [comment] 2023-05-19 13:22
@shubhamcoc is willing to pick this up

**Comment by shubhamcoc** [comment] 2023-05-19 16:33
@panyuenlau yes i can pick this up

**Comment by panyuenlau** [comment] 2023-06-22 15:13
Closing this as @shubhamcoc's commits should cover the ask here

**Closed by panyuenlau** 2023-06-22 15:13 UTC
Labels: enhancement, help wanted, good first issue, community
