### ISSUE TITLE
Problem with CC topic creation 

### ISSUE THREAD

**Issue by borisputerka** [banzaicloud/koperator#240] opened 2019-12-31 16:45 UTC
**Describe the bug**
Once in a while, when I create zookeeper and then `KafkaCluster`, operator can't create CC topicm because it already exists. Zookeeper is fresh new with its own disks so KafkaCluster is. When I list topics via kafka tools, it is true, that CC topic exists. This happened like in 4 out of 30 instances I created. Frist it gives this this error log
```{"level":"info","ts":1577806999.984675,"logger":"controllers.KafkaCluster","msg":"CR status updated","kafkacluster":"riv/kafka","Request.Name":"kafka","component":"kafka-cruisecontrol","status":"CruiseControlTopicNotReady"}
{"level":"info","ts":1577806999.9847436,"logger":"controllers.KafkaCluster","msg":"A new resource was not found or may not be ready","kafkacluster":"riv/kafka","Request.Name":"kafka"}
{"level":"info","ts":1577806999.9847531,"logger":"controllers.KafkaCluster","msg":"not enough brokers available (at least three needed) for CC topic: admission webhook \"kafkatopics.kafka.banzaicloud.io\" denied the request: Replication factor is larger than the number of nodes in the kafka cluster","kafkacluster":"riv/kafka","Request.Name":"kafka"}
{"level":"info","ts":1577806999.9848156,"logger":"controllers.KafkaCluster","msg":"Reconciling KafkaCluster","kafkacluster":"riv/kafka","Request.Name":"kafka"}
```
After all brokers come live it gives
```
{"level":"info","ts":1577807042.9541788,"logger":"controllers.KafkaCluster","msg":"CR status updated","kafkacluster":"riv/kafka","Request.Name":"kafka","component":"kafka-cruisecontrol","status":"CruiseControlTopicNotReady"}
{"level":"info","ts":1577807042.954241,"logger":"controllers.KafkaCluster","msg":"could not create cruise control topic: admission webhook \"kafkatopics.kafka.banzaicloud.io\" denied the request: Topic '__CruiseControlMetrics' already exists on kafka cluster 'kafka'","kafkacluster":"riv/kafka","Request.Name":"kafka"}
{"level":"error","ts":1577807042.9542706,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"kafkacluster","request":"riv/kafka","error":"could not create cruise control topic: admission webhook \"kafkatopics.kafka.banzaicloud.io\" denied the request: Topic '__CruiseControlMetrics' already exists on kafka cluster 'kafka'","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:218\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:192\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0/pkg/internal/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88"}
```
After that I need to delete `sts` of zookeeper, delete `kind: KafkaCluster` and their `pv` and `pvc`. Then I create the same way zookeeper and kaflacluster and everything is fine.

I need to mention that CruiseControl deployment was not created. Only after steps above operator was able to create cruisecontrol and its topic via CRD.

It is really strange because on most of namespaces it worked fine. I use one operator to handle all namespaces with kafkacluster.

**Steps to reproduce the issue:**
Create zookeeper `sts`
Create `KafkaCluster` with 3 brokers

**Comment by borisputerka** [comment] 2020-01-04 17:27
Happened to me also today. Main problem was that CC couldn't start. There was no deployment for CC. But CC topic was created in kafka after I listed all topic via kafka tools

**Comment by baluchicken** [comment] 2020-01-08 14:54
Hi @borisputerka sorry for the delayed response. 
This error occurs because Pravega's Zookeeper operator does not remove the cluster PVC once the CR is removed. So a newly created ZK cluster will reuse the orphan PVC. 
It is a bug in the operator which is fixed on the master branch but did not released yet. To fix this issue please remove not just the Zookeeper CR but the ZK PVCs as well.

**Comment by borisputerka** [comment] 2020-01-08 15:09
Hi, I am not using zookeeper via Pravega's operator. I use zookeeper as statefull set with headless service.

**Comment by baluchicken** [comment] 2020-01-08 15:28
Can you verify that the ZK PVC creation time is the same as the ZK pod creation time?

**Comment by borisputerka** [comment] 2020-01-08 16:55
I recreated the problem and these are the timestamps of zk and its pvcs
```
kpo | grep zoo && k get pvc 
zookeeper-0                           1/1     Running   0          4m1s
zookeeper-1                           1/1     Running   0          4m1s
zookeeper-2                           1/1     Running   0          4m1s
zookeeper-exporter-8499599d77-c2zcz   1/1     Running   3          4m
NAME                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-zookeeper-0     Bound    pvc-fc0ad62f-3236-11ea-9adf-42010a8400a8   8Gi        RWO            standard       4m1s
data-zookeeper-1     Bound    pvc-fc0ce8d2-3236-11ea-9adf-42010a8400a8   8Gi        RWO            standard       4m1s
data-zookeeper-2     Bound    pvc-fc0edc97-3236-11ea-9adf-42010a8400a8   8Gi        RWO            standard       4m1s

```

**Comment by borisputerka** [comment] 2020-01-08 17:24
I did the same on new cluster where there was only one kafka cluster a everythinbg was fine. This setup above was on gke cluster with 29 namespaces where each namespaces has kafkacluster and there is one opoerator watching all the namespaces. Operator has enough resources so it is not restarting.

**Comment by borisputerka** [comment] 2020-01-08 18:12
I also see that replication factor doesn't match on already created topics see:
```
k exec -it $(kubectl get pods | grep kafka[a-z0-9] | head -1 | awk '{print $1}') -- /bin/bash -c 'unset KAFKA_OPTS && /opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper-headless:2181 --describe | grep __Cru' | head -1
Topic:__CruiseControlMetrics	PartitionCount:12	ReplicationFactor:1	Configs:
```
```
k describe kafkatopics kafka-cruise-control-topic | grep Repl
  Replication Factor:  3
```
and operator is giving error that cannot change replication factor on already created topics

**Comment by borisputerka** [comment] 2020-01-08 19:17
I mean we do not even need CruiseControl in our setup. So is there any possibility now or in the future to use this operator without CC ?

**Comment by baluchicken** [comment] 2020-01-09 09:03
Hi, Kafka requires to use different ZK path/ Kafka cluster. I am guessing you are using a single Zookeeper with the same path on all Kafka clusters. Please check the official Kafka documentation about that: https://kafka.apache.org/documentation/#brokerconfigs.

To verify please send two of your Kafka cluster CR `zkAddresses` part.

To overcome this you have two options:
- Use completely isolated ZK for every Kafka cluster.
- Use unique ZK paths for every Kafka cluster.

Unfortunately due to a bug in the operator see [here](https://github.com/banzaicloud/kafka-operator/pull/236), now you cannot use unique ZK paths since the CC won't start.

Regarding your earlier question:
>  This leads me to another question whether there is option to not to use CC in this setup
The operator relies on a CC in a way that it cannot be turned off. You have the ability to provide your own CC by providing the address in the CR where the operator can connect to it.

**Comment by borisputerka** [comment] 2020-01-09 15:35
I am using ZK and KafkaCluster per namespace so each kafkacluster has its own zookeeper in that namespace.
```
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    app: kafka
    group: kafka-k8s
  name: kafka
spec:
  headlessServiceEnabled: true
  zkAddresses:
    - "zookeeper-headless:2181"
  oneBrokerPerNode: false
  clusterImage: wurstmeister/kafka{{ kafka_image_tag|image_tag }}
  brokers: 
{% for i in range(kafka_cluster_size) %}
{% set pv_name = context.namespace + "-kafka-data-" + i|string %}
{% set disk_name = "gke-" + context.namespace + '-kafka-data-' + i|string %}
{% set size = disk_size(disk_name) ~ "Gi"%}
...
```

**Comment by baluchicken** [comment] 2020-01-10 13:44
That is odd. We will try to reproduce your issue and get back to you with our findings.

**Comment by borisputerka** [comment] 2020-01-10 15:18
currently have these kafkaclusters in different namespaces under single deployment of operator
```
NAMESPACE   NAME    AGE
<ns>         kafka   23d
<ns>         kafka   28d
<ns>         kafka   28d
<ns>         kafka   7d18h
<ns>        kafka   19d
<ns>         kafka   25d
<ns>         kafka   7d1h
<ns>         kafka   6d23h
<ns>         kafka   30d
<ns>         kafka   24d
<ns>         kafka   8d
<ns>         kafka   46h
<ns>         kafka   3d1h
<ns>         kafka   23d
<ns>         kafka   18d
<ns>         kafka   24d
<ns>         kafka   13d
<ns>         kafka   18d
<ns>         kafka   14d
<ns>         kafka   15d
<ns>         kafka   3d22h
<ns>         kafka   21d
<ns>         kafka   9d
<ns>         kafka   11d
<ns>         kafka   13d
<ns>         kafka   13d
<ns>         kafka   12d
<ns>         kafka   10d
<ns>         kafka   12d
```

**Comment by AljoschaP** [comment] 2020-05-11 08:49
I have the same problem and can say that the ZK PVC creation time is the same as the ZK pod creation time. Is there anything new on this ?

**Comment by stoader** [comment] 2020-05-11 09:08
@AljoschaP unfortunately we were not able to reproduce this issue so far.

Can you provide details steps that leads to this issue to manifest itself in your environment?

**Comment by AljoschaP** [comment] 2020-05-11 10:21
1. Start Zookeeper using Pravega Operator (Version from master)
2. Start Kafka 
3. Everything works fine
4. Cruise-Control crashes/restarts
5. It never comes back again 
___
Error message of the operator:

`{"level":"info","ts":1589191781.7782428,"logger":"webhooks","msg":"AdmissionReview for Kind=kafka.banzaicloud.io/v1alpha1, Kind=KafkaTopic, Namespace=test-persistency Name=kafka-cluster-cruise-control-topic UID=97d00c72-e2b7-48e5-9d91-4d6100d8441b patchOperation=CREATE UserInfo={system:serviceaccount:k8s-operators:default 574dce12-9ee0-4eeb-b0b1-a6b9b56b49 

 {"level":"info","ts":1589191781.778365,"logger":"webhooks","msg":"Doing pre-admission validation of kafka topic __CruiseControlMetrics"}                                                                                                                                                                                                                               

{"level":"info","ts":1589191782.0615757,"logger":"webhooks","msg":"User attempted to create topic with name that already exists in the kafka cluster"}                                                                                                                                                                                                                 

{"level":"info","ts":1589191782.076798,"logger":"controllers.KafkaCluster","msg":"CR status updated","Request.Namespace":"test-persistency/kafka-cluster","Request.Name":"kafka-cluster","component":"kafka-cluster-cruisecontrol","status":"CruiseControlTopicNotReady"}                                                                                              

{"level":"info","ts":1589191782.076832,"logger":"controllers.KafkaCluster","msg":"could not create cruise control topic: admission webhook \"kafkatopics.kafka.banzaicloud.io\" denied the request: Topic '__CruiseControlMetrics' already exists on kafka cluster 'kafka-cluster'","Request.Namespace":"test-persistency/kafka-cluster","Request.Name":"kafka-cluster
 
{"level":"error","ts":1589191782.0768776,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"KafkaCluster","request":"test-persistency/kafka-cluster","error":"could not create cruise control topic: admission webhook \"kafkatopics.kafka.banzaicloud.io\" denied the request: Topic '__CruiseControlMetrics' already exists on kafka cl `

**Comment by stoader** [comment] 2020-05-11 10:27
@AljoschaP could you include your zookeepercluster and kafkacluster cr?

**Comment by AljoschaP** [comment] 2020-05-11 10:44
apiVersion: "zookeeper.pravega.io/v1beta1"
 kind: "ZookeeperCluster"
metadata:
  name: "zookeeper"
spec:
  replicas: 3
  persistence:
    volumeReclaimPolicy: Delete
    spec:
      storageClassName: fast-storage
      resources:
        requests:
          storage: 5Gi
___
apiVersion: kafka.banzaicloud.io/v1beta1
kind: KafkaCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    #app: kafka-cluster
  name: kafka-cluster
spec:
  headlessServiceEnabled: true
  zkAddresses:
    - "zookeeper-client:2181"
  propagateLabels: true
  oneBrokerPerNode: false
  clusterImage: "banzaicloud/kafka:2.13-2.4.0"
  readOnlyConfig: |
    auto.create.topics.enable=true
    delete.topic.enable=true
  brokerConfigGroups:
    default:
      storageConfigs:
        - mountPath: "/kafka-logs"
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            storageClassName: fast-storage
            resources:
              requests:
                storage: 5Gi
  brokers:
    - id: 0
      brokerConfigGroup: "default"
    - id: 1
      brokerConfigGroup: "default"
    - id: 2
      brokerConfigGroup: "default"
    - id: 3
      brokerConfigGroup: "default"
    - id: 4
      brokerConfigGroup: "default"
  rollingUpgradeConfig:
    failureThreshold: 1
  listenersConfig:
    internalListeners:
      - type: "plaintext"
        name: "internal"
        containerPort: 29092
        usedForInnerBrokerCommunication: true
      - type: "plaintext"
        name: "controller"
        containerPort: 29093
        usedForInnerBrokerCommunication: false
        usedForControllerCommunication: true
      - type: "plaintext"
        name: "plaintext"
        containerPort: 29094
        usedForInnerBrokerCommunication: true
  cruiseControlConfig:
    cruiseControlTaskSpec:
      RetryDurationMinutes: 5
    topicConfig:
      partitions: 12
      replicationFactor: 3
    config: |
      # Copyright 2017 LinkedIn Corp. Licensed under the BSD 2-Clause License (the "License"). See License in the project root for license information.
      #
      # This is an example property file for Kafka Cruise Control. See KafkaCruiseControlConfig for more details.
      # Configuration for the metadata client.
      # =======================================
      # The maximum interval in milliseconds between two metadata refreshes.
      #metadata.max.age.ms=300000
      # Client id for the Cruise Control. It is used for the metadata client.
      #client.id=kafka-cruise-control
      # The size of TCP send buffer bytes for the metadata client.
      #send.buffer.bytes=131072
      # The size of TCP receive buffer size for the metadata client.
      #receive.buffer.bytes=131072
      # The time to wait before disconnect an idle TCP connection.
      #connections.max.idle.ms=540000
      # The time to wait before reconnect to a given host.
      #reconnect.backoff.ms=50
      # The time to wait for a response from a host after sending a request.
      #request.timeout.ms=30000
      # Configurations for the load monitor
      # =======================================
      # The number of metric fetcher thread to fetch metrics for the Kafka cluster
      num.metric.fetchers=1
      # The metric sampler class
      metric.sampler.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler
      # Configurations for CruiseControlMetricsReporterSampler
      metric.reporter.topic.pattern=__CruiseControlMetrics
      # The sample store class name
      sample.store.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore
      # The config for the Kafka sample store to save the partition metric samples
      partition.metric.sample.store.topic=__KafkaCruiseControlPartitionMetricSamples
      # The config for the Kafka sample store to save the model training samples
      broker.metric.sample.store.topic=__KafkaCruiseControlModelTrainingSamples
      # The replication factor of Kafka metric sample store topic
      sample.store.topic.replication.factor=2
      # The config for the number of Kafka sample store consumer threads
      num.sample.loading.threads=8
      # The partition assignor class for the metric samplers
      metric.sampler.partition.assignor.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.DefaultMetricSamplerPartitionAssignor
      # The metric sampling interval in milliseconds
      metric.sampling.interval.ms=120000
      # The partition metrics window size in milliseconds
      partition.metrics.window.ms=300000
      # The number of partition metric windows to keep in memory
      num.partition.metrics.windows=1
      # The minimum partition metric samples required for a partition in each window
      min.samples.per.partition.metrics.window=1
      # The broker metrics window size in milliseconds
      broker.metrics.window.ms=300000
      # The number of broker metric windows to keep in memory
      num.broker.metrics.windows=20
      # The minimum broker metric samples required for a partition in each window
      min.samples.per.broker.metrics.window=1
      # The configuration for the BrokerCapacityConfigFileResolver (supports JBOD and non-JBOD broker capacities)
      capacity.config.file=config/capacity.json
      #capacity.config.file=config/capacityJBOD.json
      # Configurations for the analyzer
      # =======================================
      # The list of goals to optimize the Kafka cluster for with pre-computed proposals
      default.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal
      # The list of supported goals
      goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PotentialNwOutGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.kafkaassigner.KafkaAssignerDiskUsageDistributionGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.PreferredLeaderElectionGoal
      # The list of supported hard goals
      hard.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal
      # The minimum percentage of well monitored partitions out of all the partitions
      min.monitored.partition.percentage=0.95
      # The balance threshold for CPU
      cpu.balance.threshold=1.1
      # The balance threshold for disk
      disk.balance.threshold=1.1
      # The balance threshold for network inbound utilization
      network.inbound.balance.threshold=1.1
      # The balance threshold for network outbound utilization
      network.outbound.balance.threshold=1.1
      # The balance threshold for the replica count
      replica.count.balance.threshold=1.1
      # The capacity threshold for CPU in percentage
      cpu.capacity.threshold=0.8
      # The capacity threshold for disk in percentage
      disk.capacity.threshold=0.8
      # The capacity threshold for network inbound utilization in percentage
      network.inbound.capacity.threshold=0.8
      # The capacity threshold for network outbound utilization in percentage
      network.outbound.capacity.threshold=0.8
      # The threshold to define the cluster to be in a low CPU utilization state
      cpu.low.utilization.threshold=0.0
      # The threshold to define the cluster to be in a low disk utilization state
      disk.low.utilization.threshold=0.0
      # The threshold to define the cluster to be in a low network inbound utilization state
      network.inbound.low.utilization.threshold=0.0
      # The threshold to define the cluster to be in a low disk utilization state
      network.outbound.low.utilization.threshold=0.0
      # The metric anomaly percentile upper threshold
      metric.anomaly.percentile.upper.threshold=90.0
      # The metric anomaly percentile lower threshold
      metric.anomaly.percentile.lower.threshold=10.0
      # How often should the cached proposal be expired and recalculated if necessary
      proposal.expiration.ms=60000
      # The maximum number of replicas that can reside on a broker at any given time.
      max.replicas.per.broker=10000
      # The number of threads to use for proposal candidate precomputing.
      num.proposal.precompute.threads=1
      # the topics that should be excluded from the partition movement.
      #topics.excluded.from.partition.movement
      # Configurations for the executor
      # =======================================
      # The max number of partitions to move in/out on a given broker at a given time.
      num.concurrent.partition.movements.per.broker=10
      # The interval between two execution progress checks.
      execution.progress.check.interval.ms=10000
      # Configurations for anomaly detector
      # =======================================
      # The goal violation notifier class
      anomaly.notifier.class=com.linkedin.kafka.cruisecontrol.detector.notifier.SelfHealingNotifier
      # The metric anomaly finder class
      metric.anomaly.finder.class=com.linkedin.kafka.cruisecontrol.detector.KafkaMetricAnomalyFinder
      # The anomaly detection interval
      anomaly.detection.interval.ms=10000
      # The goal violation to detect.
      anomaly.detection.goals=com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal
      # The interested metrics for metric anomaly analyzer.
      metric.anomaly.analyzer.metrics=BROKER_PRODUCE_LOCAL_TIME_MS_MAX,BROKER_PRODUCE_LOCAL_TIME_MS_MEAN,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MAX,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_MEAN,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MAX,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_MEAN,BROKER_LOG_FLUSH_TIME_MS_MAX,BROKER_LOG_FLUSH_TIME_MS_MEAN
      ## Adjust accordingly if your metrics reporter is an older version and does not produce these metrics.
      #metric.anomaly.analyzer.metrics=BROKER_PRODUCE_LOCAL_TIME_MS_50TH,BROKER_PRODUCE_LOCAL_TIME_MS_999TH,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_50TH,BROKER_CONSUMER_FETCH_LOCAL_TIME_MS_999TH,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_50TH,BROKER_FOLLOWER_FETCH_LOCAL_TIME_MS_999TH,BROKER_LOG_FLUSH_TIME_MS_50TH,BROKER_LOG_FLUSH_TIME_MS_999TH
      # The zk path to store failed broker information.
      failed.brokers.zk.path=/CruiseControlBrokerList
      # Topic config provider class
      topic.config.provider.class=com.linkedin.kafka.cruisecontrol.config.KafkaTopicConfigProvider
      # The cluster configurations for the KafkaTopicConfigProvider
      cluster.configs.file=config/clusterConfigs.json
      # The maximum time in milliseconds to store the response and access details of a completed user task.
      completed.user.task.retention.time.ms=21600000
      # The maximum time in milliseconds to retain the demotion history of brokers.
      demotion.history.retention.time.ms=86400000
      # The maximum number of completed user tasks for which the response and access details will be cached.
      max.cached.completed.user.tasks=100
      # The maximum number of user tasks for concurrently running in async endpoints across all users.
      max.active.user.tasks=5
      # Enable self healing for all anomaly detectors, unless the particular anomaly detector is explicitly disabled
      self.healing.enabled=true
      # Enable self healing for broker failure detector
      self.healing.broker.failure.enabled=true
      # Enable self healing for goal violation detector
      self.healing.goal.violation.enabled=true
      # Enable self healing for metric anomaly detector
      self.healing.metric.anomaly.enabled=true
      # configurations for the webserver
      # ================================
      # HTTP listen port
      webserver.http.port=9090
      # HTTP listen address
      webserver.http.address=0.0.0.0
      # Whether CORS support is enabled for API or not
      webserver.http.cors.enabled=false
      # Value for Access-Control-Allow-Origin
      webserver.http.cors.origin=http://localhost:8080/
      # Value for Access-Control-Request-Method
      webserver.http.cors.allowmethods=OPTIONS,GET,POST
      # Headers that should be exposed to the Browser (Webapp)
      # This is a special header that is used by the
      # User Tasks subsystem and should be explicitly
      # Enabled when CORS mode is used as part of the
      # Admin Interface
      webserver.http.cors.exposeheaders=User-Task-ID
      # REST API default prefix
      # (dont forget the ending *)
      webserver.api.urlprefix=/kafkacruisecontrol/*
      # Location where the Cruise Control frontend is deployed
      webserver.ui.diskpath=./cruise-control-ui/dist/
      # URL path prefix for UI
      # (dont forget the ending *)
      webserver.ui.urlprefix=/*
      # Time After which request is converted to Async
      webserver.request.maxBlockTimeMs=10000
      # Default Session Expiry Period
      webserver.session.maxExpiryTimeMs=60000
      # Session cookie path
      webserver.session.path=/
      # Server Access Logs
      webserver.accesslog.enabled=true
      # Location of HTTP Request Logs
      webserver.accesslog.path=access.log
      # HTTP Request Log retention days
      webserver.accesslog.retention.days=14
    clusterConfig: |
      {
        "min.insync.replicas": 3
      }

**Comment by stoader** [comment] 2020-05-11 11:35
@AljoschaP what version of Kafka-operator are you using?

Can you try creating a KafkaCluster CR with specific Zk Path ?
```
zkAddresses:
- "zookeeper-client:2181"
zkPath: "/kafka-1"
```

**Comment by ssandanshi** [comment] 2020-09-01 20:58
We are experiencing a similar issue. The only work-around that worked was deleting zookeeper and kafka cluster PVCs and reinstalling them.

This solution does not work in the long term. Every time we delete the PVCs, We lose persistent data. Any help would be appreciated.

**Comment by vayyappaneni** [comment] 2020-09-02 02:07
we are also having the same issue,  8 out of 10 times I am having this issue. Every time we have the issue we are forced to delete all Kafka cluster and zookeeper resources and recreate again.

**Comment by baluchicken** [comment] 2022-01-12 08:39
This issue is stale for a while and there are couple of enhancements regarding how the operator creates the CC related topics. Please reopen if the issue happening again.

**Closed by baluchicken** 2022-01-12 08:39 UTC
Labels: community
